# learning Numpy

In [1]:
import numpy as np

In [2]:
np.array(10)

array(10)

In [3]:
x = np.array([11,22,33,44])

In [4]:
x

array([11, 22, 33, 44])

In [5]:
x.shape

(4,)

In [6]:
x.ndim

1

In [7]:
x.size

4

In [8]:
type(x)

numpy.ndarray

In [9]:
x.dtype

dtype('int32')

In [10]:
type(x)

numpy.ndarray

In [11]:
x.shape

(4,)

In [12]:
x.ndim

1

In [13]:
x.size

4

In [14]:
arr1d = np.arange(10)

In [15]:
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
type(arr1d)

numpy.ndarray

In [17]:
arr2d = np.array([[1,2,3,4], [11,22,33,44], [111,222,333,444], [1111,2222,3333,4444]])

In [18]:
arr2d

array([[   1,    2,    3,    4],
       [  11,   22,   33,   44],
       [ 111,  222,  333,  444],
       [1111, 2222, 3333, 4444]])

In [19]:
arr2d.size

16

In [20]:
arr2d[1]

array([11, 22, 33, 44])

In [21]:
arr2d.shape

(4, 4)

In [22]:
# arr2d = np.arange(20).reshape(1,20)
# arr2d = np.arange(20).reshape(20, 1)
# arr2d = np.arange(20).reshape(4,5)
arr2d = np.arange(20).reshape(5,4)
# arr2d = np.arange(20).reshape(2,10)
# arr2d = np.arange(20).reshape(10,2)

In [23]:
arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [24]:
arr2d[4,3]

19

In [25]:
arr1d.shape

(10,)

In [26]:
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr1d[9]

9

In [28]:
arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [29]:
arr2d = arr2d.reshape(20)

In [30]:
arr2d.shape

(20,)

In [31]:
arr2d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [32]:
arr2d.size

20

In [33]:
arr2d[3]

3

In [34]:
arr2d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [35]:
arr2d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [36]:
arr2d[4]

4

In [37]:
arr2d = arr2d.reshape(4,5)

In [38]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [39]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [40]:
arr2d = arr2d.reshape(20)

In [41]:
arr2d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [42]:
arr2d = arr2d.reshape(4,5)

In [43]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [46]:
arr2d = arr2d.flatten()

In [47]:
arr2d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [48]:
arr2d = arr2d.reshape(4,5)

In [49]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [50]:
arr2d.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [51]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [52]:
arr2d = arr2d.ravel()

In [53]:
arr2d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [54]:
arr2d = arr2d.reshape(4,5)

In [55]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [56]:
arr = np.arange(20)

In [57]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [59]:
arr.shape

(20,)

In [61]:
print(arr.ndim)

1


In [64]:
arr3d = np.arange(64).reshape(4,4,4)

In [65]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [74]:
arr3d[2,0]

array([32, 33, 34, 35])

In [87]:
arr3d[3,0,0:3]

array([48, 49, 50])

In [89]:
arr3d[3,0,0]*5

240

In [90]:
arr3d[3,0,0] = arr3d[3,0,0]*5

In [91]:
arr3d[3,0,0]

240

In [92]:
arr3d

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [ 12,  13,  14,  15]],

       [[ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [ 24,  25,  26,  27],
        [ 28,  29,  30,  31]],

       [[ 32,  33,  34,  35],
        [ 36,  37,  38,  39],
        [ 40,  41,  42,  43],
        [ 44,  45,  46,  47]],

       [[240,  49,  50,  51],
        [ 52,  53,  54,  55],
        [ 56,  57,  58,  59],
        [ 60,  61,  62,  63]]])

In [93]:
arr3d*100

array([[[    0,   100,   200,   300],
        [  400,   500,   600,   700],
        [  800,   900,  1000,  1100],
        [ 1200,  1300,  1400,  1500]],

       [[ 1600,  1700,  1800,  1900],
        [ 2000,  2100,  2200,  2300],
        [ 2400,  2500,  2600,  2700],
        [ 2800,  2900,  3000,  3100]],

       [[ 3200,  3300,  3400,  3500],
        [ 3600,  3700,  3800,  3900],
        [ 4000,  4100,  4200,  4300],
        [ 4400,  4500,  4600,  4700]],

       [[24000,  4900,  5000,  5100],
        [ 5200,  5300,  5400,  5500],
        [ 5600,  5700,  5800,  5900],
        [ 6000,  6100,  6200,  6300]]])

In [94]:
arr3d = 0

In [95]:
arr3d

0

In [96]:
arr3d = np.arange(64).reshape(4,4,4)

In [97]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [98]:
arr3d * 0 

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [99]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [101]:
y = np.arange(4)

In [102]:
y

array([0, 1, 2, 3])

In [103]:
y.ndim

1

In [104]:
y.shape

(4,)

In [106]:
y.size

4

In [107]:
y.size

4

In [108]:
x

array([11, 22, 33, 44])

In [109]:
x+y

array([11, 23, 35, 47])

In [111]:
x * y

array([  0,  22,  66, 132])

In [112]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [115]:
arr2d[0:1, 0:5]

array([[0, 1, 2, 3, 4]])

In [118]:
arr2d[0:4, 0:1] = arr2d[0:4, 0:1] * 200

In [119]:
arr2d

array([[   0,    1,    2,    3,    4],
       [1000,    6,    7,    8,    9],
       [2000,   11,   12,   13,   14],
       [3000,   16,   17,   18,   19]])

In [123]:
arr2d[:, 0:0]

array([], shape=(4, 0), dtype=int32)

In [124]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [126]:
arr3d[3:4, 0:4, 0:1]

array([[[48],
        [52],
        [56],
        [60]]])

In [128]:
arr3d[3:4, 0:4, 0:1] > 58

array([[[False],
        [False],
        [False],
        [ True]]])

In [129]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

### querrying array 

In [130]:
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [131]:
arr1d>4

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [133]:
arr1d % 2 == 0, "yes", "no"

(array([ True, False,  True, False,  True, False,  True, False,  True,
        False]),
 'yes',
 'no')

In [134]:
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [135]:
mask = arr1d > 5

In [137]:
arr1d[mask]

array([6, 7, 8, 9])

In [138]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [141]:
mask = arr3d > 15 == 0

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [140]:
arr3d[mask]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [143]:
arr3d.any(44)

AxisError: axis 44 is out of bounds for array of dimension 3

In [146]:
np.where(arr1d>4, 0, arr1d*20)

array([ 0, 20, 40, 60, 80,  0,  0,  0,  0,  0])

In [147]:
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])